table sensitivity_filter_missing
	lineageTag: 88746ea0-408a-4fb5-9b33-052db6dfc018

	column hypothesis
		dataType: string
		lineageTag: b5e6f98d-aae1-4595-b474-16f3eafe1cbf
		summarizeBy: none
		sourceColumn: hypothesis

		annotation SummarizationSetBy = Automatic

	column hypothesis_id
		dataType: string
		lineageTag: 6ad9f5a7-00f8-41ab-82fd-2e88f9a9b6c3
		summarizeBy: none
		sourceColumn: hypothesis_id

		annotation SummarizationSetBy = Automatic

	column spec
		dataType: string
		lineageTag: 5b2bb13c-e0e8-477d-8d77-504a8defaad2
		summarizeBy: none
		sourceColumn: spec

		annotation SummarizationSetBy = Automatic

	column primary_diff_pp
		dataType: double
		lineageTag: 9f5e37e4-d061-416b-a1b2-b56c1b530673
		summarizeBy: sum
		sourceColumn: primary_diff_pp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column primary_ci_pp
		dataType: string
		lineageTag: b352c1b7-8c79-40b2-9dcf-43c9f9b2aa94
		summarizeBy: none
		sourceColumn: primary_ci_pp

		annotation SummarizationSetBy = Automatic

	column primary_p
		dataType: double
		lineageTag: e140ab3f-8bb6-423c-9ce1-8c6ba834cd70
		summarizeBy: sum
		sourceColumn: primary_p

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sensitivity_diff_pp
		dataType: double
		lineageTag: 3aef78e9-f6c0-4a7c-ac1e-3804176e4c3f
		summarizeBy: sum
		sourceColumn: sensitivity_diff_pp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sensitivity_ci_pp
		dataType: string
		lineageTag: 001ce7d2-16dd-49ed-b8fb-3cb812441e61
		summarizeBy: none
		sourceColumn: sensitivity_ci_pp

		annotation SummarizationSetBy = Automatic

	column sensitivity_p
		dataType: double
		lineageTag: 19e5f1dc-ddf1-4b34-91f1-c08454190d88
		summarizeBy: sum
		sourceColumn: sensitivity_p

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sign_agrees
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2f13ee05-a6a3-4616-b599-ca4a7992041e
		summarizeBy: none
		sourceColumn: sign_agrees

		annotation SummarizationSetBy = Automatic

	column 'both_null_at_0.05'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a249b73-0b34-428b-a7c5-d76339148fbd
		summarizeBy: none
		sourceColumn: both_null_at_0.05

		annotation SummarizationSetBy = Automatic

	partition sensitivity_filter_missing = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("<path-to-this-repo>\outputs\tables\sensitivity_filter_missing.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"hypothesis", type text}, {"hypothesis_id", type text}, {"spec", type text}, {"primary_diff_pp", type number}, {"primary_ci_pp", type text}, {"primary_p", type number}, {"sensitivity_diff_pp", type number}, {"sensitivity_ci_pp", type text}, {"sensitivity_p", type number}, {"sign_agrees", type logical}, {"both_null_at_0.05", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

